---
- name: Install Apache Web Server
  hosts: rhel
  gather_facts: True

  tasks:

    - name: Install Apache
      package:
        name:
          - httpd
      become: yes    

    - name: Create test web page
      include_role:
        name: "./roles/rhel_test_webpage"      