---

- name: Copy Index page
  win_copy:
    src: ./roles/rhel_test_webpage/files/index.html
    dest: C:\Inetpub\wwwroot\
- name: Copy Red Hat Ansible Image
  win_copy:
    src: ./roles/rhel_test_webpage/files/rh_ansible.jpg
    dest: C:\Inetpub\wwwroot\