---

- name: Copy index page
  copy:
    src: ./roles/rhel_test_webpage/files/index.html
    dest: /var/www/html/
  become: yes  

- name: Copy Red Hat Ansible Image
  copy:
    src: ./roles/rhel_test_webpage/files/rh_ansible.jpg
    dest: /var/www/html/
  become: yes

- name: Copy Red Hat Enterprise Linux 8 Image
  copy:
    src: ./roles/rhel_test_webpage/files/rhel8.png
    dest: /var/www/html/
  become: yes  